spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tbank-cooldown-api
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  web:
    error:
      include-message: always

logging:
  level:
    root: INFO
    org.svids.tbankcooldownapi.service: DEBUG

server:
  port: 8080

scraping:
  api:
    key: ${SCRAPPING_KEY}
    url: ${SCRAPPING_URL}
  timeoutms: 60

tunnel:
  url: ${TUNNEL_URL}
